### ISSUE TITLE
Add an include_namespaces attribute to the TagNode.xpath method

### ISSUE THREAD

**Issue by JKatzwinkel** [delb-xml/delb-py#53]
[Let's assume](https://content.staatsbibliothek-berlin.de/dc/PPN718708741.mets.xml) a node at some level below root defines its own namespace without its parents knowing anything about that namespace. Any attempt at addressing said node or any of its descendants in the namespace it defines from the root node would fail because for the root node, that's an illegal namespace. The `nsmap` itself of a node can't be modified neither.

Therefore, the `TagNode.xpath` method should have an optional parameter via which you can declare additional namespaces to be used for evaluating the xpath expression.

**Comment by funkyfuture** [comment]
i already typed in a solution where the additional argument is named `namespace` in my current working tree on the XPath parser / evaluator.

**Comment by JKatzwinkel** [comment]
isnt "bug" a bit harsh?

**Comment by funkyfuture** [comment]
no, because bad design decisions are hard to overcome in the future (or improper design is worse than improper implementation). okay in this case it wouldn't be too hard to fix.

i'm closing here as it is already present in the current XPath implementation.
