### ISSUE TITLE
descendant-or-self axis in TagNode.xpath method

### ISSUE THREAD

**Issue by JKatzwinkel** [delb-xml/delb-py#72]
The `xpath` method in `TagNode` behaves counter-intuitively when handling relative (`descendant-or-self`) xpath expressions.

For my convenience's sake, let me show this using the OAI-PMH schema conforming XML response from https://oai.sbb.berlin/?verb=ListRecords&metadataPrefix=mets&set=illustrierte.liedflugschriften. Imagine one would want to extract bibliographic data from each record in the list of records the response provides:

```python
doc = Document('https://oai.sbb.berlin/?verb=ListRecords&metadataPrefix=mets&set=illustrierte.liedflugschriften')
records = doc.xpath('//ListRecords/record')
record = records[0]
```

Intuitively, one could choose to use a relative xpath expression against each one of those `record` tagnodes:

```python
creator = record.xpath(
    '//metadata/oai_dc:dc/dc:creator',
    {
        'dc': 'http://purl.org/dc/elements/1.1/',
        'oai_dc': 'http://www.openarchives.org/OAI/2.0/oai_dc/'
    }
)
```

However, the results are not what one would expect, which is a list of only one single `TagNode` (representing `<dc:creator .../>`), but rather the results contain every single `<dc:creator/>` node from every single `<record>` node!

**Comment by funkyfuture** [comment]
a simple reproduction of the bug would be this, correct?

```python
def test_evaluation_scope():
    first_record = Document(
        '''<root>
               <ListRecords>
                   <record>
                   <metadata/>
                   </record>
                   <record>
                   <metadata/>
                   </record>
               </ListRecords>
           </root>'''
    ).xpath('//ListRecords/record').first
    assert len(first_record.xpath("//metadata")) == 1
```

**Comment by JKatzwinkel** [comment]
yes, that is almost exactly what I would have changed that test to, too.

**Comment by JKatzwinkel** [comment]
yep, that (49b11977e20b7078793ebd1a7a8654898bf13c88) is what I was talking about.

**Comment by funkyfuture** [comment]
actually the issue is rather an XPath design bug. at least the test suite has a reminder now: b94726c8ec8932cdb32e8f03d399219733f1b54a
