### ISSUE TITLE
drop python 3.7 support

### ISSUE THREAD

**Issue by JKatzwinkel** [delb-xml/delb-py#76]
python 3.7 is EOL.

**Comment by funkyfuture** [comment]
yes, but i still need it for a while.

**Comment by funkyfuture** [comment]
i won't need it anymore.

my proposal is the following:
as keeping the support isn't a burden atm, i'd stick with the plan to drop it with 0.6.
for the native-model-implementing 0.6 release 3.9 will be required. dict unions and more typing clarity are takeways. and i don't expect that release much earlier (if at all) before 3.8 settles.

it's not unlikely though that i'll insert another 0.6 target just (or rather mainly) for specifying parser-related interfaces. then i'd say that 0.7 will require 3.9.
